function updateEnemies(dt){for(let e of enemies){if(e.dead)continue;e.cd-=dt;e.stun-=dt;if(e.stun>0)continue;let dx=player.x-e.x,dy=player.y-e.y,d=Math.hypot(dx,dy)||1,nx=dx/d,ny=dy/d;
 if(e.kind==='grunt'||e.kind==='elite'){moveEntity(e,nx*e.sp*dt,ny*e.sp*dt);if(d<e.r+player.r+7)hurt(e.dmg*dt*2.3)}
 else if(e.kind==='shooter'){let desired=d>270?1:d<190?-1:0;moveEntity(e,nx*e.sp*desired*dt,ny*e.sp*desired*dt);if(e.cd<=0){e.cd=1.2+Math.random()*.45;shootEnemy(e,Math.atan2(dy,dx),300,1)}}
 else if(e.kind==='drone'){e.phase+=dt*2.2;let tx=nx*Math.cos(.45)+ny*Math.sin(.45),ty=ny*Math.cos(.45)-nx*Math.sin(.45);moveEntity(e,tx*e.sp*dt,ty*e.sp*dt);if(e.cd<=0){e.cd=1.0;shootEnemy(e,Math.atan2(dy,dx),340,1)}}
 else if(e.kind==='charger'){if(e.charge>0){e.charge-=dt;moveEntity(e,e.vx*dt,e.vy*dt);if(d<e.r+player.r+5)hurt(e.dmg)}else if(e.cd<=0&&d<420){e.cd=2.2;e.charge=.45;e.vx=nx*440;e.vy=ny*440;particles.push({type:'warn',x:e.x,y:e.y,a:Math.atan2(dy,dx),l:.35,m:.35});sound(120,.12,'sawtooth',.02,180)}else moveEntity(e,nx*e.sp*.7*dt,ny*e.sp*.7*dt)}
 else if(e.kind==='boss'){e.angle+=dt;let phase=e.hp/e.maxHp<.5?2:1;e.phase=phase;if(e.archetype==='queen'){let tx=Math.cos(e.angle*.8)*.55+nx*.15,ty=Math.sin(e.angle*.8)*.55+ny*.15;moveEntity(e,tx*e.sp*dt,ty*e.sp*dt);e.summon-=dt;if(e.summon<=0){e.summon=phase===2?2.1:3.0;spawnEnemy('drone');if(phase===2)spawnEnemy('drone');toast('THE QUEEN RELEASES DRONES')}if(e.cd<=0){e.cd=phase===2?.48:.75;shootEnemy(e,e.angle,275,phase===2?5:3,.28)}}else if(e.archetype==='knight'){if(e.charge>0){e.charge-=dt;moveEntity(e,e.vx*dt,e.vy*dt);if(d<e.r+player.r+8)hurt(e.dmg)}else if(e.cd<=0){e.cd=phase===2?1.05:1.45;e.charge=.36;e.vx=nx*(phase===2?600:500);e.vy=ny*(phase===2?600:500);particles.push({type:'warn',x:e.x,y:e.y,a:Math.atan2(dy,dx),l:.4,m:.4})}else moveEntity(e,nx*e.sp*.45*dt,ny*e.sp*.45*dt)}else{let tx=Math.cos(e.angle*.7)*.65+nx*.25,ty=Math.sin(e.angle*.7)*.65+ny*.25;moveEntity(e,tx*e.sp*dt,ty*e.sp*dt);if(e.cd<=0){if(phase===1){e.cd=.85;shootEnemy(e,Math.atan2(dy,dx),330,3,.18)}else{e.cd=.58;for(let j=0;j<10;j++)shootEnemy(e,e.angle+j/10*6.28,260,1)}}}if(d<e.r+player.r+5)hurt(e.dmg*dt*1.6)}
 }
 enemies=enemies.filter(e=>!e.dead);
 if((roomType==='combat'||roomType==='elite')&&enemies.length===0&&gameState==='play')roomCleared(false);
}
function roomCleared(fromBoss){if(transition)return;transition=1;toast('ROOM CLEARED');$('objective').textContent='ROOM CLEARED';sound(520,.18,'triangle',.035,400);setTimeout(()=>{transition=0;if(fromBoss){floor++;bestFloor=Math.max(bestFloor,floor);saveMeta();showUpgrade('newFloor')}else if(roomIndex>=4)showUpgrade('boss');else if(roomIndex%2===0)showUpgrade('route');else showRoomSelect()},650)}
const roomPool=[{type:'combat',icon:'⚔️',name:'Assault Wing',desc:'Standard combat room. Reliable rewards.'},{type:'elite',icon:'☠️',name:'Elite Lockdown',desc:'Harder enemies. Better credit payout.'},{type:'treasure',icon:'◈',name:'Data Cache',desc:'Open a cache for a free augment.'},{type:'heal',icon:'✚',name:'Med Node',desc:'Restore health and shields.'},{type:'shop',icon:'◆',name:'Black Market',desc:'Spend run credits on upgrades for this run.'},{type:'survival',icon:'◷',name:'Pressure Chamber',desc:'Survive continuous enemy waves until the lock releases.'}];
function showRoomSelect(){show('roomSelect');$('pauseBtn').style.display='none';let cards=$('roomCards');cards.innerHTML='';let shuffled=[...roomPool].sort(()=>Math.random()-.5),opts=shuffled.slice(0,3);opts.forEach((o,i)=>{let b=document.createElement('button');b.className='choice';b.innerHTML=`<div class="icon">${o.icon}</div><b>${o.name}</b><small>${o.desc}</small><span class="tag">ROUTE ${i+1}</span>`;b.onclick=()=>{hideScreens();$('pauseBtn').style.display='block';gameState='play';loadRoom(o.type);last=performance.now();requestAnimationFrame(loop)};cards.appendChild(b)})}
const augments=[{n:'Vampire Edge',d:'Melee kills restore 4 HP.',r:'rare',f:()=>player.lifesteal+=4},{n:'Hollow Point',d:'+35% ranged damage.',r:'common',f:()=>player.gun*=1.35},{n:'Razor Wire',d:'+40% melee damage.',r:'common',f:()=>player.melee*=1.4},{n:'Overclock',d:'25% faster fire rate.',r:'rare',f:()=>player.gunRate*=.75},{n:'Phase Armor',d:'+15% damage reduction.',r:'epic',f:()=>player.armor=Math.min(.55,player.armor+.15)},{n:'Core Battery',d:'+35 max shield and refill it.',r:'rare',f:()=>{player.maxShield+=35;player.shield=player.maxShield}},{n:'Redline',d:'+30% movement speed.',r:'common',f:()=>player.speed*=1.3},{n:'Executioner',d:'+12% crit chance.',r:'epic',f:()=>player.crit+=.12},{n:'Singularity',d:'Burst needs 20 less charge.',r:'legendary',f:()=>player.maxEnergy=Math.max(60,player.maxEnergy-20)},{n:'Nanoforge',d:'+30 max HP and heal fully.',r:'rare',f:()=>{player.maxHp+=30;player.hp=player.maxHp}},{n:'Twin Barrel',d:'Fire one additional projectile.',r:'epic',f:()=>player.shots=Math.min(5,player.shots+1)},{n:'Ghost Rounds',d:'Bullets pierce one enemy.',r:'epic',f:()=>player.pierce++},{n:'Long Blade',d:'+35% melee reach.',r:'rare',f:()=>player.meleeRange*=1.35},{n:'Impact Dash',d:'Dash damages enemies in your path.',r:'rare',f:()=>player.dashDamage+=42},{n:'Feedback Loop',d:'Gain energy 35% faster.',r:'epic',f:()=>player.energyGain*=1.35},{n:'Aegis Harvest',d:'Kills restore 3 shield.',r:'rare',f:()=>player.killShield+=3},{n:'Blood Circuit',d:'Regenerate 1.5 HP each second.',r:'legendary',f:()=>player.regen+=1.5}];
function showUpgrade(next='route'){show('upgrade');$('pauseBtn').style.display='none';let cards=$('upgradeCards');cards.innerHTML='';let pool=[...augments].sort(()=>Math.random()-.5).slice(0,3);if(next==='newFloor')pool[0]=pick(augments.filter(a=>a.r==='epic'||a.r==='legendary'));pool.forEach(a=>{let b=document.createElement('button');b.className=`choice ${a.r}`;b.innerHTML=`<div class="icon">${a.r==='legendary'?'✦':a.r==='epic'?'✧':'◇'}</div><b>${a.n}</b><small>${a.d}</small><span class="tag">${a.r.toUpperCase()}</span>`;b.onclick=()=>{a.f();sound(620,.12,'triangle',.03,250);if(next==='newFloor'){hideScreens();$('pauseBtn').style.display='block';gameState='play';roomIndex=0;loadRoom('combat');last=performance.now();requestAnimationFrame(loop)}else if(next==='boss'){hideScreens();$('pauseBtn').style.display='block';gameState='play';loadRoom('boss');last=performance.now();requestAnimationFrame(loop)}else showRoomSelect()};cards.appendChild(b)})}
function openShop(){show('shop');$('pauseBtn').style.display='none';$('shopSub').textContent=`You have ${runCredits} run credits.`;let items=[{n:'Field Repair',d:'Restore 45 HP.',p:10,f:()=>player.hp=clamp(player.hp+45,0,player.maxHp)},{n:'Shield Cell',d:'Refill shields.',p:8,f:()=>player.shield=player.maxShield},{n:'Weapon Tune',d:'+20% gun and melee damage.',p:18,f:()=>{player.gun*=1.2;player.melee*=1.2}}],cards=$('shopCards');cards.innerHTML='';items.forEach(it=>{let b=document.createElement('button');b.className='choice';b.innerHTML=`<div class="icon">◆</div><b>${it.n}</b><small>${it.d}</small><div class="price">${it.p} CREDITS</div>`;b.onclick=()=>{if(runCredits<it.p){toast('NOT ENOUGH CREDITS');return}runCredits-=it.p;it.f();b.disabled=true;b.style.opacity=.45;$('shopSub').textContent=`You have ${runCredits} run credits.`;sound(680,.08,'triangle',.03)};cards.appendChild(b)})}
$('leaveShop').onclick=()=>{interactable.used=true;hideScreens();$('pauseBtn').style.display='block';gameState='play';roomCleared(false);last=performance.now();requestAnimationFrame(loop)};