'use strict';
const c=document.getElementById('game'),ctx=c.getContext('2d'),mini=document.getElementById('minimap'),mctx=mini.getContext('2d');
const $=id=>document.getElementById(id), clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), rand=(a,b)=>a+Math.random()*(b-a), pick=a=>a[(Math.random()*a.length)|0], lerp=(a,b,t)=>a+(b-a)*t;
let DPR=1,W=0,H=0,last=performance.now(),gameState='menu',difficulty='normal',roomType='combat',roomIndex=0,floor=1,kills=0,runCredits=0,totalCredits=+(localStorage.brCredits||0),bestFloor=+(localStorage.brBest||0),runs=+(localStorage.brRuns||0),screenshake=0,flash=0,slowmo=0,transition=0;
let keys={},joy={id:null,x:0,y:0,dx:0,dy:0},loadout='vanguard',roomTimer=0,waveTimer=0;let metaHP=+(localStorage.brMetaHP||0),metaPower=+(localStorage.brMetaPower||0),metaShield=+(localStorage.brMetaShield||0);
let walls=[],enemies=[],bullets=[],enemyBullets=[],particles=[],drops=[],props=[],doors=[],boss=null,interactable=null;
let player={x:0,y:0,vx:0,vy:0,r:17,hp:100,maxHp:100,shield:35,maxShield:35,energy:0,maxEnergy:100,speed:235,melee:28,gun:18,gunRate:.22,gunCd:0,meleeCd:0,dashCd:0,dashTime:0,inv:0,crit:.08,critMult:2,range:520,magnet:80,lifesteal:0,armor:0,coins:0,weapon:'pulse rifle',blade:'shock blade',shots:1,pierce:0,meleeRange:112,dashDamage:0,energyGain:1,bulletSpeed:620,regen:0,killShield:0};
const saveMeta=()=>{localStorage.brCredits=totalCredits;localStorage.brBest=bestFloor;localStorage.brRuns=runs;localStorage.brMetaHP=metaHP;localStorage.brMetaPower=metaPower;localStorage.brMetaShield=metaShield};
function resize(){DPR=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;c.width=W*DPR;c.height=H*DPR;c.style.width=W+'px';c.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0);mini.width=180;mini.height=112;mini.style.width='90px';mini.style.height='56px';}
addEventListener('resize',resize);resize();
let audio=null;function sound(f=300,d=.05,type='sine',v=.02,slide=0){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,f+slide),audio.currentTime+d);g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
const vibrate=p=>{try{navigator.vibrate?.(p)}catch{}};
function toast(t){let e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),900)}
function banner(top,bottom=''){let e=$('roomBanner');e.innerHTML=`<small>${bottom}</small>${top}`;e.classList.add('show');clearTimeout(banner.t);banner.t=setTimeout(()=>e.classList.remove('show'),1000)}
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('show'));$(id).classList.add('show');gameState=id}
function hideScreens(){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('show'));}
function metaUI(){$('metaBest').textContent=bestFloor;$('metaCredits').textContent=totalCredits;$('metaRuns').textContent=runs}metaUI();
document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{difficulty=b.dataset.diff;document.querySelectorAll('[data-diff]').forEach(x=>x.classList.toggle('active',x===b));sound(460,.05,'triangle',.02)});document.querySelectorAll('[data-loadout]').forEach(b=>b.onclick=()=>{loadout=b.dataset.loadout;document.querySelectorAll('[data-loadout]').forEach(x=>x.classList.toggle('activeLoad',x===b));sound(540,.05,'triangle',.02)});
function resetPlayer(){player={x:W/2,y:H*.63,vx:0,vy:0,r:17,hp:100,maxHp:100,shield:35,maxShield:35,energy:0,maxEnergy:100,speed:235,melee:28,gun:18,gunRate:.22,gunCd:0,meleeCd:0,dashCd:0,dashTime:0,inv:0,crit:.08,critMult:2,range:520,magnet:80,lifesteal:0,armor:0,coins:0,weapon:'pulse rifle',blade:'shock blade',shots:1,pierce:0,meleeRange:112,dashDamage:0,energyGain:1,bulletSpeed:620,regen:0,killShield:0};if(loadout==='gunner'){player.gun=22;player.gunRate=.16;player.melee=20;player.crit=.15;player.maxShield=25;player.shield=25;player.weapon='VX carbine'}else if(loadout==='reaper'){player.melee=39;player.speed=270;player.maxShield=18;player.shield=18;player.gun=14;player.meleeRange=126;player.blade='void cleaver'}else{player.melee=32;player.maxShield=48;player.shield=48;player.gun=17;player.weapon='warden rifle'}player.maxHp+=metaHP*6;player.hp=player.maxHp;player.maxShield+=metaShield*5;player.shield=player.maxShield;let pm=1+metaPower*.045;player.gun*=pm;player.melee*=pm}
function startRun(){floor=1;roomIndex=0;kills=0;runCredits=0;roomType='combat';resetPlayer();hideScreens();$('pauseBtn').style.display='block';loadRoom('combat',true);gameState='play';last=performance.now();sound(170,.22,'sawtooth',.045,380);requestAnimationFrame(loop)}
function openArmory(){show('armory');renderArmory()}function renderArmory(){$('armorySub').textContent=`BANK: ${totalCredits} CREDITS • Upgrades apply to every future run.`;let cards=$('armoryCards');cards.innerHTML='';let defs=[{n:'Reinforced Frame',d:'+6 starting max HP per level.',get:()=>metaHP,set:v=>metaHP=v,max:12},{n:'Weapons Lab',d:'+4.5% starting melee and gun damage per level.',get:()=>metaPower,set:v=>metaPower=v,max:12},{n:'Aegis Core',d:'+5 starting shield per level.',get:()=>metaShield,set:v=>metaShield=v,max:12}];defs.forEach((it,i)=>{let lv=it.get(),cost=45+lv*35,b=document.createElement('button');b.className='choice';b.innerHTML=`<div class="icon">${i===0?'▣':i===1?'⌁':'◉'}</div><b>${it.n} • LV ${lv}/${it.max}</b><small>${it.d}</small><div class="price">${lv>=it.max?'MAXED':cost+' CREDITS'}</div>`;b.onclick=()=>{if(lv>=it.max)return;if(totalCredits<cost){toast('NOT ENOUGH CREDITS');return}totalCredits-=cost;it.set(lv+1);saveMeta();metaUI();sound(720,.12,'triangle',.03,250);renderArmory()};cards.appendChild(b)})} $('armoryBtn').onclick=openArmory;$('leaveArmory').onclick=()=>{show('menu');metaUI()};
$('startBtn').onclick=startRun;$('retryBtn').onclick=startRun;$('menuBtn').onclick=()=>{$('pauseBtn').style.display='none';show('menu');metaUI()};
$('pauseBtn').onclick=()=>{if(gameState==='play'){show('pause');$('pauseBtn').style.display='none'}};$('resumeBtn').onclick=()=>{hideScreens();gameState='play';$('pauseBtn').style.display='block';last=performance.now();requestAnimationFrame(loop)};$('quitBtn').onclick=()=>endRun(true);
function rectWall(x,y,w,h){walls.push({x,y,w,h})}
function makeArena(type){walls=[];props=[];doors=[];interactable=null;const pad=22, top=92, bottom=H-28;rectWall(0,0,W,top);rectWall(0,bottom,W,H-bottom);rectWall(0,0,pad,H);rectWall(W-pad,0,pad,H);const patterns=['pillars','lanes','cross','open'];let p=pick(patterns);if(type==='boss')p='open'; if(type==='shop'||type==='treasure'||type==='heal')p='pillars';if(p==='pillars'){let ys=[H*.36,H*.62];for(let y of ys){rectWall(W*.25-28,y-28,56,56);rectWall(W*.75-28,y-28,56,56)}}if(p==='lanes'){rectWall(W*.2,H*.38,W*.23,26);rectWall(W*.58,H*.6,W*.23,26)}if(p==='cross'){rectWall(W*.46,H*.3,W*.08,H*.18);rectWall(W*.46,H*.6,W*.08,H*.18);rectWall(W*.18,H*.49,W*.22,22);rectWall(W*.6,H*.49,W*.22,22)}for(let i=0;i<10;i++)props.push({x:rand(55,W-55),y:rand(top+40,bottom-40),r:rand(5,13),t:Math.random()});}
function clearEntities(){enemies=[];bullets=[];enemyBullets=[];particles=[];drops=[];boss=null;}