function loadRoom(type,first=false){roomType=type;clearEntities();makeArena(type);player.x=W/2;player.y=H*.7;player.vx=player.vy=0;player.inv=1;roomIndex++;$('stageText').textContent=`${floor}-${roomIndex}`;banner(type==='boss'?'CORE WARDEN':type.toUpperCase(),`FLOOR ${floor} • ROOM ${roomIndex}`);
 let n=3+Math.floor(floor*.7)+Math.floor(roomIndex*.25); if(difficulty==='hard')n+=2;
 if(type==='combat'){for(let i=0;i<n;i++)spawnEnemy(i<2?'grunt':null);$('objective').textContent='CLEAR THE ROOM'}
 if(type==='survival'){roomTimer=18+floor*1.5;waveTimer=0;for(let i=0;i<3;i++)spawnEnemy();$('objective').textContent='SURVIVE THE WAVE'}
 if(type==='elite'){for(let i=0;i<Math.max(2,n-2);i++)spawnEnemy(i===0?'elite':null);$('objective').textContent='ELIMINATE THE ELITE'}
 if(type==='boss'){spawnBoss();$('objective').textContent='DEFEAT THE BOSS'}
 if(type==='treasure'){spawnChest();$('objective').textContent='OPEN THE CACHE'}
 if(type==='heal'){spawnHealNode();$('objective').textContent='USE THE MED NODE'}
 if(type==='shop'){spawnShopNode();$('objective').textContent='ACCESS THE BLACK MARKET'}
 if(first)toast('RUN STARTED');
}
function safePos(){for(let k=0;k<80;k++){let x=rand(60,W-60),y=rand(125,H-70);if(Math.hypot(x-player.x,y-player.y)>180&&!walls.some(w=>circleRect(x,y,24,w)))return{x,y}}return{x:W/2,y:140}}
function spawnEnemy(force){let p=safePos(),r=Math.random(),kind=force|| (r<.42?'grunt':r<.67?'shooter':r<.84?'charger':'drone');let base=1+(floor-1)*.18+(difficulty==='hard'?.25:0);let data={grunt:{hp:44,sp:82,r:18,dmg:14},shooter:{hp:34,sp:62,r:17,dmg:10},charger:{hp:58,sp:72,r:20,dmg:20},drone:{hp:28,sp:105,r:14,dmg:9},elite:{hp:150,sp:90,r:24,dmg:22}}[kind];enemies.push({x:p.x,y:p.y,vx:0,vy:0,kind,r:data.r,hp:data.hp*base,maxHp:data.hp*base,sp:data.sp*(1+floor*.02),dmg:data.dmg*base,cd:rand(.3,1.1),charge:0,stun:0,elite:kind==='elite',dead:false,phase:Math.random()*6.28})}
function spawnBoss(){let base=1+(floor-1)*.25+(difficulty==='hard'?.35:0),types=['warden','queen','knight'],archetype=types[(floor-1)%types.length],stats=archetype==='knight'?{hp:760,sp:92,dmg:28}:archetype==='queen'?{hp:650,sp:64,dmg:18}:{hp:620,sp:72,dmg:22};boss={x:W/2,y:160,vx:0,vy:0,r:46,hp:stats.hp*base,maxHp:stats.hp*base,sp:stats.sp,dmg:stats.dmg*base,cd:.8,phase:1,dead:false,kind:'boss',archetype,angle:0,summon:2.5,charge:0};enemies.push(boss);banner(archetype==='queen'?'SWARM QUEEN':archetype==='knight'?'NULL KNIGHT':'CORE WARDEN','BOSS ENCOUNTER')}
function spawnChest(){interactable={type:'chest',x:W/2,y:H*.42,r:35,used:false}}
function spawnHealNode(){interactable={type:'heal',x:W/2,y:H*.42,r:34,used:false}}
function spawnShopNode(){interactable={type:'shop',x:W/2,y:H*.42,r:36,used:false}}
function circleRect(x,y,r,w){let cx=clamp(x,w.x,w.x+w.w),cy=clamp(y,w.y,w.y+w.h);return (x-cx)**2+(y-cy)**2<r*r}
function moveEntity(e,dx,dy){e.x+=dx;for(let w of walls)if(circleRect(e.x,e.y,e.r,w)){if(dx>0)e.x=w.x-e.r;if(dx<0)e.x=w.x+w.w+e.r}e.y+=dy;for(let w of walls)if(circleRect(e.x,e.y,e.r,w)){if(dy>0)e.y=w.y-e.r;if(dy<0)e.y=w.y+w.h+e.r}}
function nearestEnemy(max=9999){let best=null,bd=max;for(let e of enemies){if(e.dead)continue;let d=Math.hypot(e.x-player.x,e.y-player.y);if(d<bd){bd=d;best=e}}return best}
function melee(){if(gameState!=='play'||player.meleeCd>0)return;player.meleeCd=.42;let target=nearestEnemy(105),ang=target?Math.atan2(target.y-player.y,target.x-player.x):Math.atan2(joy.dy||0,joy.dx||1);sound(180,.09,'sawtooth',.03,220);vibrate(12);particles.push({type:'slash',x:player.x,y:player.y,a:ang,l:.16,m:.16,range:player.meleeRange});for(let e of enemies){if(e.dead)continue;let dx=e.x-player.x,dy=e.y-player.y,d=Math.hypot(dx,dy),da=Math.abs(Math.atan2(Math.sin(Math.atan2(dy,dx)-ang),Math.cos(Math.atan2(dy,dx)-ang)));if(d<player.meleeRange&&da<1.0)damageEnemy(e,player.melee*(Math.random()<player.crit?player.critMult:1),'melee')};player.energy=clamp(player.energy+8,0,player.maxEnergy)}
function fire(){if(gameState!=='play'||player.gunCd>0)return;let target=nearestEnemy(player.range);if(!target){toast('NO TARGET');player.gunCd=.15;return}player.gunCd=player.gunRate;let base=Math.atan2(target.y-player.y,target.x-player.x);for(let i=0;i<player.shots;i++){let spread=(i-(player.shots-1)/2)*.13,a=base+spread,crit=Math.random()<player.crit;bullets.push({x:player.x+Math.cos(a)*18,y:player.y+Math.sin(a)*18,vx:Math.cos(a)*player.bulletSpeed,vy:Math.sin(a)*player.bulletSpeed,r:5,dmg:player.gun*(crit?player.critMult:1),life:1.1,crit,pierce:player.pierce})}particles.push({type:'muzzle',x:player.x,y:player.y,a:base,l:.08,m:.08});sound(420,.035,'square',.012,120)}
function dash(){if(gameState!=='play'||player.dashCd>0)return;let dx=joy.dx,dy=joy.dy;if(Math.hypot(dx,dy)<.2){let e=nearestEnemy();if(e){let a=Math.atan2(player.y-e.y,player.x-e.x);dx=Math.cos(a);dy=Math.sin(a)}else dx=1}let l=Math.hypot(dx,dy)||1;player.vx=dx/l*720;player.vy=dy/l*720;player.dashTime=.18;player.dashCd=1.6;player.inv=.32;screenshake=6;particles.push({type:'dash',x:player.x,y:player.y,l:.25,m:.25});sound(90,.12,'sawtooth',.03,450);vibrate(18)}
function burst(){if(gameState!=='play'||player.energy<player.maxEnergy)return;player.energy=0;player.inv=.6;screenshake=18;flash=.7;sound(75,.35,'sawtooth',.06,600);vibrate([20,30,35]);for(let i=0;i<48;i++){let a=i/48*6.28;particles.push({type:'spark',x:player.x,y:player.y,vx:Math.cos(a)*rand(120,380),vy:Math.sin(a)*rand(120,380),l:.7,m:.7,c:'#c46cff'})}for(let e of enemies){if(!e.dead&&Math.hypot(e.x-player.x,e.y-player.y)<270)damageEnemy(e,95+floor*8,'burst')}enemyBullets=[];toast('VOID BURST')}
$('attack').onclick=melee;$('shoot').onclick=fire;$('dash').onclick=dash;$('special').onclick=burst;
function damageEnemy(e,dmg,src){if(e.dead)return;e.hp-=dmg;e.stun=Math.max(e.stun,.06);particles.push({type:'hit',x:e.x,y:e.y,l:.18,m:.18,c:src==='burst'?'#c770ff':src==='melee'?'#ff668f':'#59e7ff'});if(e.hp<=0)killEnemy(e)}
function killEnemy(e){if(e.dead)return;e.dead=true;kills++;player.energy=clamp(player.energy+(e.kind==='boss'?35:12)*player.energyGain,0,player.maxEnergy);if(player.killShield>0)player.shield=clamp(player.shield+player.killShield,0,player.maxShield);let reward=e.kind==='boss'?18:e.elite?7:Math.random()<.18?2:1;runCredits+=reward;totalCredits+=reward;saveMeta();for(let i=0;i<(e.kind==='boss'?28:10);i++){let a=Math.random()*6.28,s=rand(35,e.kind==='boss'?260:150);particles.push({type:'spark',x:e.x,y:e.y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,l:rand(.25,.75),m:.75,c:e.kind==='boss'?'#ffd166':'#ff567d'})}if(player.lifesteal>0)player.hp=clamp(player.hp+player.lifesteal,0,player.maxHp);sound(e.kind==='boss'?80:150,e.kind==='boss'?.4:.08,'sawtooth',e.kind==='boss'?.05:.018,100);if(e.kind==='boss'){let bn=e.archetype==='queen'?'SWARM QUEEN':e.archetype==='knight'?'NULL KNIGHT':'CORE WARDEN';boss=null;toast(bn+' DOWN');setTimeout(()=>roomCleared(true),700)}}
function hurt(d){if(player.inv>0)return;d*=1-player.armor;if(player.shield>0){let take=Math.min(player.shield,d);player.shield-=take;d-=take}if(d>0)player.hp-=d;player.inv=.55;screenshake=10;flash=.45;vibrate(22);sound(110,.1,'sawtooth',.035,40);if(player.hp<=0)endRun(false)}
function shootEnemy(e,a,speed=310,count=1,spread=.18){for(let i=0;i<count;i++){let off=(i-(count-1)/2)*spread,aa=a+off;enemyBullets.push({x:e.x,y:e.y,vx:Math.cos(aa)*speed,vy:Math.sin(aa)*speed,r:e.kind==='boss'?7:5,dmg:e.dmg,life:3})}sound(180,.04,'square',.008)}